
name: Production CI/CD

on:
  push:
    branches:
      - main

jobs:
  staging_test:
    name: Run Tests on Staging
    runs-on: ubuntu-latest
    steps:
      - name: SSH and run tests on Staging
        uses: appleboy/ssh-action@v1.0.0
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSHE_SSH_KEY }}
          script: bash /app/deploy.sh yuka_misawa --test

  deploy_production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: staging_test   # ← staging_job が成功したら動く
    steps:
      - name: SSH and deploy to Production
        uses: appleboy/ssh-action@v1.0.0
        with:
          SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
          SSH_PORT: ${{ secrets.PROD_SSH_PORT }}
          SSH_USER: ${{ secrets.PROD_SSH_USER }}
          SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
          script: bash /app/deploy.sh yuka_misawa
